version: '3'

services:
  node: 
    container_name: chat_app_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports: 
      - 4000:4000
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo-express
    # command: > 
    #   bash -c "npm install && npm start"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: chat_app_db
    volumes:
      - database:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    
volumes:
    database:
