version: '3'

services:
  node: 
    container_name: chat_app_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - phpmyadmin
    command: npm start
  
  db:
    image: mariadb:10.4.21
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_app_db
      MYSQL_USER: quangnd.nta
      MYSQL_PASSWORD: Aa22032001!
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
