version: '3'

services:
  node: 
    container_name: chat_app_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - app:/app
    depends_on:
      - mongo-express
    command: > 
      bash -c "npm install && npm start"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: chat_app_db
    volumes:
      - database:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    
  # db:
  #   image: mariadb:10.4.21
  #   restart: always
  #   environment:
  #     MYSQL_HOST: localhost
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: chat_app_db
  #     MYSQL_USER: quangnd.nta
  #     MYSQL_PASSWORD: Aa22032001!
  #   volumes:
  #      - database:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   command: --default-authentication-plugin=mysql_native_password

  # # phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
      
volumes:
    database:
    app:
